### ISSUE TITLE
[EPIC] Revise front-end and api of Conservation (EQIP, CRP, CSP...)

### ISSUE THREAD

**Issue by pengyin-shan** [policy-design-lab/pdl-frontend#207]
## Linked Issues
- [ ] Update API so that Conservation follows the same pattern as the new Title I & Crop Insurance pattern
- [ ] [Need Discussion] Update top-line/landing page API to follow the same pattern as the new Title I & Crop Insurance pattern
- [ ] Update Frontend of the Conversation to 1) have fewer components 2) follow the new API
- [ ] Update landing page map to follow new API pattern
- https://github.com/policy-design-lab/pdl-api/issues/149
