### ISSUE TITLE
[EPIC] Surface 51 Migration Project

### ISSUE THREAD

**Issue by pengyin-shan** [policy-design-lab/pdl-frontend#244]
## Description
This Epic is for tracking the Surface 51 development/migration project

## Linked Issues
- [x] #245
- [ ] Vite migration to webpack
- [ ] SASS/CSS code re-write
- [ ] Scripts re-write
- [ ] API or CSV/JSON re-write
- [ ] Designer's review/update
